### ISSUE TITLE
[Bug]: Card always empty, "No results"

### ISSUE THREAD

**Issue by moghwan** [denniseilander/pulse-log-files#2]
### What happened?

after installing and registering the package and the recorder, the card always loads without any logfile name, while im having at least one.

### How to reproduce the bug

accessing laravel pulse dashboard

### Package Version

0.1.0

### PHP Version

8.2.14

### Laravel Version

10.41.0

### Which operating systems does with happen with?

Linux

### Notes

while debugging, running **record** function code inside **__construct()** (without $event) did the job, still not sure why it doesn't run the **record** function
_file: vendor/denniseilander/pulse-log-files/src/Recorders/LogFiles.php_

**Comment by denniseilander** [comment]
Hi @moghwan, thank you for reporting the issue!

I'll investigate the "No results" bug today and keep you updated.

**Comment by denniseilander** [comment]
Hi @moghwan,

I attempted to replicate the bug you mentioned, but didn't encounter it on my end.

Just to double-check, have you run `php artisan pulse:check` in your application where pulse-log-files is installed?
Running `php artisan pulse:check` is essential as it's responsible for data storage in the database. If this step is missed, the card will not show any records.

**Comment by moghwan** [comment]
hi @denniseilander, just checked again and it was my bad, Supervisor was not running and after restarting it it's all working like a charm! many thanks. closing issue as resolved.

**Comment by denniseilander** [comment]
Hi @moghwan, thanks for double checking and nice to hear it is working now! Have a nice day! :)
